on:
  push:
    branches:
        - main

name: Create Release

jobs:
  publish-to-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - name: Install latest npm version
      run: npm install -g npm@latest
    - name: Install dependencies and build
      run: npm ci

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish-to-npm
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: install semantic
        run: npx semantic-release@master
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}